name: firesockets
description: Firesockets library
version: 0.0.1+1
homepage: https://github.com/mauriciotogneri/firesockets

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  daunused: ^1.7.4
  dapublock: ^1.1.0
  flutter_lints: ^6.0.0
